### ISSUE TITLE
Minimum font size

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#10]
The minimum font size is extremely small, almost readable.
To be able to read properly, it is necessary to set the cursor almost to the maximum.
Is it possible to do something about this? The current index 35 should almost have to be the new index 1 of the cursor in my opinion.

**Comment by fulvio999** [comment]
Strange,The slider range is from 1 to 50.
35 is not the max value.
Have you modified the system font settings with 'UT tweak tool, App ?
What phone are you using ?
There is no correct font size in the 1-50 range for your device?
 i could try set a range from 20 to 70 but values greater than 50 are maybe to bigger...
thanks

**Comment by gbdomubpkm** [comment]
You right 35 is not the maximum but with a BQ E5 HD, I must use at least 40 for a normal readability.

Changing settings in UT T T does not change the size of the initial font in the document formatting. You can check it out.

My current value used in UT T T  is 17.

![settings UTT](https://user-images.githubusercontent.com/50362604/65388952-10798680-dd51-11e9-9860-6931d9a20e88.png)

Several full-size screen shots  to get an idea of the situation as it is currently not possible to display several different font sizes in the same document. Hence the idea of having a larger font size at the beginning.

![cursor 10](https://user-images.githubusercontent.com/50362604/65388984-50d90480-dd51-11e9-9cc4-3767fc1f64f9.png)
![CURSOR 20](https://user-images.githubusercontent.com/50362604/65388985-55052200-dd51-11e9-9244-0bbc867f3c59.png)
![CURSOR 30](https://user-images.githubusercontent.com/50362604/65388986-55052200-dd51-11e9-9a3e-e46e53237b40.png)
![CURSOR 40](https://user-images.githubusercontent.com/50362604/65388987-55052200-dd51-11e9-9da1-901b0c699222.png)
![CURSOR 50](https://user-images.githubusercontent.com/50362604/65388988-559db880-dd51-11e9-9f21-c3b91c46322c.png)

**Comment by fulvio999** [comment]
Ok, understand. I'll try to set a bigger  range like 20 - 80 due the fact that the partition from 1 to 15 has no sense.

**Comment by gbdomubpkm** [comment]
That's right and thank you.

**Comment by fulvio999** [comment]
fix released with version 2.3.5 available in the openstore

**Comment by gbdomubpkm** [comment]
Perfect ! 👍
