### ISSUE TITLE
Word Wrap?

### ISSUE THREAD

**Issue by Connorabruce** [fulvio999/tedit#11]
The original edit program had a wordwrap function that worked really well. While Tedit appears to have one (the placeholder text is wrapped) when I start typing it doesn't wrap at all. 

I can't find the setting for WordWrap in Settings (where it was in edit). Am I missing something? Is it somewhere else? No-one else seems to have mentioned this, so I assume I'm just missing the setting?

**Comment by fulvio999** [comment]
yes, you're right, i have missed it. i'll release the fix next days.

**Comment by fulvio999** [comment]
enhancement/fix released with version 2.4 available in the Openstore

**Comment by Connorabruce** [comment]
That's awesome, thanks!
