### ISSUE TITLE
Tedit on PinePhone

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#12]
On the PinePhone, in the OpenStore app, the Teddit app does not appear in the app list. I assume that this app is not currently compatible with the PinePhone?  This seems to be confirmed from the OpenStore website: from there, Teddit appears but the .click cannot be installed.

**Comment by fulvio999** [comment]
Yes, currently there no Tedit version for PinePhone. Is necessary create a dedicated build version. I'll try to build and publish it next days if i'll have time.

**Comment by fulvio999** [comment]
Tedit 2.6 package for arm64 arch is now in the Openstore (i can test download because i don't have PinePhone)

**Comment by gbdomubpkm** [comment]
Thank you !
I have a Pinephone but not on hand now. If it's not someone else, I'll let you know within 3 days.

**Comment by gbdomubpkm** [comment]
It's okay.  Tedit installed and running normally.  It's a little slower than with OPO though.

**Comment by fulvio999** [comment]
ok thanks. I close the issue. About the app speed i think is related at the device hardware.
