### ISSUE TITLE
[request] port to focal

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#21]
Please update your essential app to focal if needed. Your app is a real document safe for me. I haven't switched to focal yet,  my 16.04 Volla is too personalized and stable for that, the focal ported environment (app) insufficient currently for me,  but at least other 20.04 users will be able to test. Thanks in advance.

**Comment by fulvio999** [comment]
Hi gbdomubpkm
sorry but i have no time to maintain my Apps and stay updated with the last UBports developments :( 
I'm looking for a new maintainer/developer [](https://forums.ubports.com/topic/8639/looking-for-a-new-apps-maintainer)
Regards

**Comment by gbdomubpkm** [comment]
Hi @fulvio999 
I understand but that would be a very big loss for focal !
I think you should quickly  post a message on the forum for information.
Regards

**Comment by gbdomubpkm** [comment]
I saw you did it 🙂 !
