### ISSUE TITLE
 Extra lines pasting into Telegram

### ISSUE THREAD

**Issue by CesarHerreraG** [fulvio999/tedit#4]
When select text, copy and paste it appear in the beginning tree strange lines:
p, li { white-space: pre-wrap; }

test

**Comment by fulvio999** [comment]
sorry but i can't reproduce the issue. I  have tried with copy and paste from different sources (Telegram chat included) but the problem does not appear.
Please provide more details (like the source where i have copied the text)

**Comment by CesarHerreraG** [comment]
I start tedit and write test
Go to  Select all
copy to clipboard
Go to Telegram and paste
And obtain:
 Cesar Herrera, [09.08.19 16:45]
p, li { white-space: pre-wrap; }


test

**Comment by CesarHerreraG** [comment]
/home/c/Imágenes/Captura de pantalla -2019-08-09 16-50-12.png
