### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#5]
Hello.
Happy to see new recent updates done.
I always liked this very useful app and put it in the spotlight.
My request will be quite general: continue to develop it by making it as close as possible to a word processor if possible: choice of font size, choice of font color, background color of an area, bold, underlined.....
Thank you and good luck.

**Comment by fulvio999** [comment]
Hello. Thanks !
Make the app close to a word processor is not easy, are necessary some C++ skills that i don't have, and also more time to develop. 
But i think that the purpose of Tedit App is just "a quick & simple notes application", to have a complete word editor i suggest "uWriter" or "Seabass" App in the Openstore.
About some features you suggest i'm working on.
Regards
