### ISSUE TITLE
Bug when displaying menus in landscape mode

### ISSUE THREAD

**Issue by gbdomubpkm** [fulvio999/tedit#9]
Observed on NEXUS 5 and BQ E5 HD, probably for all phones. NOT on BQ M10 tablet.

Both menus (general menu and settings) cannot be displayed in full in landscape mode. A good part of it is not visible. The menus as they stand are not scrolling. If you could do that, srolling menus would be good i think (for both portrait and landscape mode) for display of future options.

**Comment by fulvio999** [comment]
ok, understood

**Comment by fulvio999** [comment]
fix released with version 2.3.3 in the Openstore

**Comment by gbdomubpkm** [comment]
Hello.

The drop-down support is not functional for the open, save... menu in landscape mode. The unwinding goes up by letting go of the finger.

The drop-down support is ok for the settings menu.

**Comment by fulvio999** [comment]
Hello,
The menu popup does not scroll ?
Or the open, save popup should be  scrollable?
All the menu entry can be used and visibile? Sorry but i have the tablet and simulate the phone is not easy 
Can You paste some screenshot if possibile? Thanks

**Comment by gbdomubpkm** [comment]
Tested on BQ E5 HD but surely the same thing for each phone.
Initial menu landscape mode
![menu1](https://user-images.githubusercontent.com/50362604/64446577-71f6ef80-d0d9-11e9-9c86-d2f2eddc7694.png)
Maximum unwinding obtained by holding and raising the finger on the screen
![menu2](https://user-images.githubusercontent.com/50362604/64446718-d5811d00-d0d9-11e9-8be1-635ffc32ddee.png)
If i release my finger, i go back to the first screenshot

**Comment by fulvio999** [comment]
fix released with version 2.3.4 in the Openstore. Reopen the issue if the bug persist

**Comment by gbdomubpkm** [comment]
I confirm that the bug is fixed.
Good work.
